# Generated by Django 2.0.6 on 2018-06-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Id', models.CharField(max_length=20, verbose_name='_id')),
                ('user_name', models.CharField(max_length=20, verbose_name='_name')),
                ('user_email', models.CharField(max_length=20, verbose_name='_email')),
            ],
            options={
                'ordering': ['-user_Id'],
            },
        ),
    ]
